require('node:fs').mkdirSync(require('node:path').join(__dirname,'artifacts'),{recursive:true});
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('assert/strict'),fs=require('fs');
(async()=>{
const b=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL || 'msedge'}),page=await b.newPage({viewport:{width:1440,height:900}}),errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto((process.env.GAME_URL || 'http://127.0.0.1:4173'));await page.click('#startBtn');await page.waitForTimeout(80);
const state=()=>page.evaluate(()=>finalNoticeSnapshot());
assert.equal((await state()).phase,'playing');checks.push('Start screen enters active game');
const bounds=await page.locator('#board').boundingBox();
const point=(i)=>({x:bounds.x+(17+i%5*117+54)*bounds.width/610,y:bounds.y+(11+Math.floor(i/5)*91+40)*bounds.height/400});
let p=point(0);await page.mouse.move(p.x,p.y);await page.mouse.down();await page.waitForTimeout(480);await page.mouse.up();assert.deepEqual((await state()).path,[0]);checks.push('Mouse rubbing physically reveals seal');
await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');assert.deepEqual((await state()).path,[0,1]);checks.push('Keyboard reveals connected next seal');
const before=await state();await page.keyboard.press('ArrowDown');await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');assert.deepEqual((await state()).path,[0,1]);checks.push('Disconnected moves rejected');
await page.keyboard.press('KeyF');assert.equal((await state()).bank,before.pot);assert.equal((await state()).pot,0);checks.push('Bank claims transfer the correct payout');
await page.keyboard.press('Escape');let paused=await state();await page.waitForTimeout(300);assert.equal((await state()).timeLeft,paused.timeLeft);assert.equal((await page.locator('#pausePanel').isVisible()),true);checks.push('Pause freezes time and shows instructions');await page.click('#resumeBtn');
await page.keyboard.down('Space');assert.equal((await state()).quiet,true);await page.keyboard.press('Enter');assert.equal((await state()).path.length,0);await page.keyboard.up('Space');assert.equal((await state()).quiet,false);checks.push('Hold breath blocks scratches and releases correctly');
await page.keyboard.press('Enter');await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');assert((await state()).pot>=12);const bankBefore=(await state()).bank;await page.click('#decoy0');assert.equal((await state()).pot,0);assert.equal((await state()).bank,bankBefore);assert.equal((await state()).stats.decoys,1);checks.push('Echo burns unbanked claim without spending bank');
await page.click('#lane1');assert.equal((await state()).selectedLane,1);checks.push('Camera switches active noise route');
await page.click('#soundBtn');assert.equal(await page.locator('#soundBtn').textContent(),'SOUND OFF');checks.push('Sound toggle works');
await page.screenshot({path:'tests/artifacts/desktop-900.png',fullPage:true});
let r=await page.locator('#decoy1').boundingBox();assert(r.y+r.height<=900,'Core actions below desktop fold');checks.push('Core gameplay fits 1440×900');
await page.setViewportSize({width:1366,height:768});await page.waitForTimeout(80);r=await page.locator('#decoy1').boundingBox();assert(r.y+r.height<=768,'Core actions below laptop fold');await page.screenshot({path:'tests/artifacts/laptop.png',fullPage:true});checks.push('Core gameplay fits 1366×768');
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(80);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'tests/artifacts/mobile.png',fullPage:true});checks.push('Phone layout has no horizontal clipping');
await page.setViewportSize({width:1440,height:900});await page.evaluate(()=>{finalNotice.state.lanes[0].threat=99.99;finalNotice.tick(1);});await page.waitForTimeout(70);assert.equal((await state()).phase,'lost');assert(await page.locator('#endPanel').isVisible());await page.click('#restartBtn');assert.equal((await state()).phase,'playing');assert.equal((await state()).bank,0);checks.push('Collector loss and restart recover cleanly');
await page.evaluate(()=>finalNotice.tick(90));await page.waitForTimeout(80);assert.equal((await state()).phase,'lost');assert.equal((await page.locator('#endTitle').innerText()).includes('YOUR TIME'),true);checks.push('Missing payment shows its distinct ending');
assert.deepEqual(errors,[]);checks.push('No browser runtime errors');
const local=await b.newPage({viewport:{width:1280,height:900}});await local.goto(require('node:url').pathToFileURL(require('node:path').resolve(__dirname,'../dist/index.html')).href);await local.click('#startBtn');assert.equal(await local.evaluate(()=>finalNoticeSnapshot().phase),'playing');checks.push('Standalone HTML runs directly from disk');
const touch=await b.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});await touch.goto((process.env.GAME_URL || 'http://127.0.0.1:4173'));await touch.click('#startBtn');await touch.locator('#board').scrollIntoViewIfNeeded();const tr=await touch.locator('#board').boundingBox();await touch.touchscreen.tap(tr.x+71*tr.width/610,tr.y+51*tr.height/400);await touch.touchscreen.tap(tr.x+71*tr.width/610,tr.y+51*tr.height/400);await touch.touchscreen.tap(tr.x+71*tr.width/610,tr.y+51*tr.height/400);assert.equal((await touch.evaluate(()=>finalNoticeSnapshot())).path[0],0);checks.push('Touch tapping reveals seals');
await b.close();fs.writeFileSync('tests/artifacts/browser-check-results.json',JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({passed:checks.length,checks,errors},null,2));
})().catch(e=>{console.error(e);process.exit(1)});
